# CMake generated Testfile for 
# Source directory: /home/runner/work/p3109-cpp/p3109-cpp
# Build directory: /home/runner/work/p3109-cpp/p3109-cpp/_codeql_build_dir
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[decode]=] "/home/runner/work/p3109-cpp/p3109-cpp/_codeql_build_dir/test_decode")
set_tests_properties([=[decode]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;28;add_test;/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;0;")
add_test([=[encode]=] "/home/runner/work/p3109-cpp/p3109-cpp/_codeql_build_dir/test_encode")
set_tests_properties([=[encode]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;33;add_test;/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;0;")
add_test([=[project_ops]=] "/home/runner/work/p3109-cpp/p3109-cpp/_codeql_build_dir/test_project_ops")
set_tests_properties([=[project_ops]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;38;add_test;/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;0;")
add_test([=[sqrt]=] "/home/runner/work/p3109-cpp/p3109-cpp/_codeql_build_dir/test_sqrt")
set_tests_properties([=[sqrt]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;43;add_test;/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;0;")
add_test([=[abs]=] "/home/runner/work/p3109-cpp/p3109-cpp/_codeql_build_dir/test_abs")
set_tests_properties([=[abs]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;48;add_test;/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;0;")
add_test([=[add]=] "/home/runner/work/p3109-cpp/p3109-cpp/_codeql_build_dir/test_add")
set_tests_properties([=[add]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;53;add_test;/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;0;")
add_test([=[fma]=] "/home/runner/work/p3109-cpp/p3109-cpp/_codeql_build_dir/test_fma")
set_tests_properties([=[fma]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;58;add_test;/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;0;")
add_test([=[compare_equal]=] "/home/runner/work/p3109-cpp/p3109-cpp/_codeql_build_dir/test_compare_equal")
set_tests_properties([=[compare_equal]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;63;add_test;/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;0;")
add_test([=[is_zero]=] "/home/runner/work/p3109-cpp/p3109-cpp/_codeql_build_dir/test_is_zero")
set_tests_properties([=[is_zero]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;68;add_test;/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;0;")
add_test([=[trig]=] "/home/runner/work/p3109-cpp/p3109-cpp/_codeql_build_dir/test_trig")
set_tests_properties([=[trig]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;73;add_test;/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;0;")
add_test([=[hyp]=] "/home/runner/work/p3109-cpp/p3109-cpp/_codeql_build_dir/test_hyp")
set_tests_properties([=[hyp]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;78;add_test;/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;0;")
add_test([=[inv_trig]=] "/home/runner/work/p3109-cpp/p3109-cpp/_codeql_build_dir/test_inv_trig")
set_tests_properties([=[inv_trig]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;83;add_test;/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;0;")
add_test([=[exp_log]=] "/home/runner/work/p3109-cpp/p3109-cpp/_codeql_build_dir/test_exp_log")
set_tests_properties([=[exp_log]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;88;add_test;/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;0;")
add_test([=[arith]=] "/home/runner/work/p3109-cpp/p3109-cpp/_codeql_build_dir/test_arith")
set_tests_properties([=[arith]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;93;add_test;/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;0;")
add_test([=[atan2]=] "/home/runner/work/p3109-cpp/p3109-cpp/_codeql_build_dir/test_atan2")
set_tests_properties([=[atan2]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;98;add_test;/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;0;")
add_test([=[minmax]=] "/home/runner/work/p3109-cpp/p3109-cpp/_codeql_build_dir/test_minmax")
set_tests_properties([=[minmax]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;103;add_test;/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;0;")
add_test([=[compare_pred]=] "/home/runner/work/p3109-cpp/p3109-cpp/_codeql_build_dir/test_compare_pred")
set_tests_properties([=[compare_pred]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;108;add_test;/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;0;")
add_test([=[ternary]=] "/home/runner/work/p3109-cpp/p3109-cpp/_codeql_build_dir/test_ternary")
set_tests_properties([=[ternary]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;113;add_test;/home/runner/work/p3109-cpp/p3109-cpp/CMakeLists.txt;0;")
